//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberDumber.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101")]
        public string UserAgent {
            get {
                return ((string)(this["UserAgent"]));
            }
            set {
                this["UserAgent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")]
        public string Accept {
            get {
                return ((string)(this["Accept"]));
            }
            set {
                this["Accept"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("__cfduid=dacfca29466ac5c2607ddf60a87b1a95a1437560815; truecaller-session=eyJpdiI6" +
            "IkdqWlM1U3dKNlZYU3Zmcmo0NE1KOXRVVVJJR3dQZjZkV0tHdjBhbHVVZzg9IiwidmFsdWUiOiJsQTFx" +
            "TWZjTWtoNStHWTFuUWFEbnkwK3ZtWmNNXC9ZZGgzMWVQc0N2cTBXa2xqNkZmeUNxd1RBV21vblFYNmVi" +
            "bGk0cFhmRjMxelpVUlwvMjZuaUZVWWNBPT0iLCJtYWMiOiI4NjhkN2RiNzc0N2YxYWFhZTZhYzkyYzE3" +
            "ZTI3NjVkM2I2NTc5MzY5ZDI3YzUyNGQ1YWQxNTc0ZDlkMzZiOWRkIn0%3D; AB_SearchSignIn=eyJp" +
            "diI6IktFTHBINTNrSmd0YVc2dWNcL011Wk9zdjk3cm9kSmV3dWliNXR4cVFnNDdNPSIsInZhbHVlIjoi" +
            "b1pPNmZGVzBOXC85bkZKWDFpYVdqXC8wYXdneURYMmRKWklVRTYyTng1RVdrPSIsIm1hYyI6ImZjZDUw" +
            "YzllOWY1MDNlNDVhMWRjYTI5YmMyZjQzY2ExOWQxMmNjZjViYjA5NDQ2OGZhMjI2ZmVhMDhmMmNkZjgi" +
            "fQ%3D%3D; XLBS2=XLBS2|Va9wa|Va9v8; _ga=GA1.2.200213827.1437560823; _gat=1; user=" +
            "eyJpdiI6ImxLNWZneTZPWDdUbFJtcDJMc1ZCbEtlXC9VS0NQOTRpckw0QUttdzl5MXlBPSIsInZhbHVl" +
            "IjoiUkNxMlFsVm4xOHA1T09ldFNQNmNXV0lqU1dhSzhSY2o3eWNZZ1VDdVRxcjZZZWxMMENTV1wvVGFS" +
            "Q0tJZ0NPa1djXC9xU2kzcDNvTFNyNWVJTEc0TlQrMXJxOUd2ZVFLSzVjSno5dUUxTk1YbXVkNG81Vlpm" +
            "RzRXWEtCcTVFY1M1NGg2OHJJejZKSTE1UCtxdFRlK2hydWdJM1B3cWRHOTU2NHgzbnFYYk1HenowS2NM" +
            "TWdGOWhUQjZDc1o1M0lacnZKU0MzdXgxamVcLzVmSklPU1ZpVmM3RWZsVUl6T2F1eDVOUFlKa1UzcWVi" +
            "WlV5cVJjQjdlQkNmZjNUUGpkVjlwZ2hvU2ZmR0lnUnJsZjRuRXpTMDJ0MDg1TmVkbWg2ZGU1cWFHSFFv" +
            "OXozZitFWE50YmtpUmZcL1Zjd0p6MXJ1c3RpSVwvXC9JY0pleWVsRkt0Z0ZlSGxHejhxVGp2MzI3ek9v" +
            "cFF5dDMzUzVrTHVKY0FNSGI5Z1pcL2xRdUZpMDFqN3NjcVc1MnlMVUhxWXVjTWY4R1dENThjRExxd0tp" +
            "UXlJb1h1UlcyRmRkU3NOelo2c1wvYVdHNDJPelc3QlYxN2NIeUU5Y0tsOTU3dFpuRmJVOWNjTjNhVElz" +
            "b0FWaWxFaGNrYzFKMG5CYlFLajlHblVqMlFRZHpMMG1yK1MzQnY4dlJHWlN1ZVVmMzNCRmhzZXR6SHR4" +
            "NXBxYktUVTBkREN0WWRXZis4bkVkZFwvRFdSMmZ5b2t3aVcxV3JrT3d0bUx3WWM3WlozdUpiN2tsdXNI" +
            "VTRwenNWWndiaHVtK2llTmExRmVLWlwvTnVTVTM3ZlNvSm1BTHNGckJ6S3ZcL1gwT3BkXC9CMjZlZ3pD" +
            "QjRNdllGT1hhSk94SjdwXC9ZXC85aUJBUlJcL1BSSzkxQzNuY3lLYk40TmY1NnR6SWZ6SGt5NUFtVEh6" +
            "R25JdzgreHZ6Z21zcnIrTGluZU53Vk1JckpYZ1FmZUdpaTk1KzZqVzFkS3Z3bHB5QzJRcFpWQ0VtRE10" +
            "WG5uQUxCIiwibWFjIjoiYjZlMjA0OWYwNTNhOTY0MmQzNjgyMWViNWZlYjIxY2JhZjg0ZmIzMzM4ODcz" +
            "MmNmMmVlOTE4NDgyMjZkZTQ0MiJ9; PHPSESSID=igvbsbodhvo4bauuck9vb46r73")]
        public string Cookie {
            get {
                return ((string)(this["Cookie"]));
            }
            set {
                this["Cookie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DbPath {
            get {
                return ((string)(this["DbPath"]));
            }
            set {
                this["DbPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDumbed {
            get {
                return ((string)(this["LastDumbed"]));
            }
            set {
                this["LastDumbed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SessionExpired {
            get {
                return ((bool)(this["SessionExpired"]));
            }
            set {
                this["SessionExpired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("011")]
        public string LastPrefix {
            get {
                return ((string)(this["LastPrefix"]));
            }
            set {
                this["LastPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("93")]
        public int LastRangeFrom {
            get {
                return ((int)(this["LastRangeFrom"]));
            }
            set {
                this["LastRangeFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("143")]
        public int LastRangeTo {
            get {
                return ((int)(this["LastRangeTo"]));
            }
            set {
                this["LastRangeTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int LastLength {
            get {
                return ((int)(this["LastLength"]));
            }
            set {
                this["LastLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ad")]
        public string LastSearchedName {
            get {
                return ((string)(this["LastSearchedName"]));
            }
            set {
                this["LastSearchedName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01111014041")]
        public string LastSearchedNumber {
            get {
                return ((string)(this["LastSearchedNumber"]));
            }
            set {
                this["LastSearchedNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int LastCountryIndex {
            get {
                return ((int)(this["LastCountryIndex"]));
            }
            set {
                this["LastCountryIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LastTabIndex {
            get {
                return ((int)(this["LastTabIndex"]));
            }
            set {
                this["LastTabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoadImageFromWeb {
            get {
                return ((bool)(this["LoadImageFromWeb"]));
            }
            set {
                this["LoadImageFromWeb"] = value;
            }
        }
    }
}
